const Data = [
    {
        id: "1",
        name: "Kedjenou de pondeuse",
        price: 1500,
        favorite: true,
        cookTime: "40-50",
        origins: ["Abbey" , "CI"],
        stars: 3.5,
        imageUrl: "image1.jpg",
        tags:["Kédjénou" , "kédjénou avec pondeuse"],
    },
    {
        id: "2",
        name: "Kedjenou de poisson",
        price: 1200,
        favorite: false,
        cookTime: "30-40",
        origins: ["Abbey" , "CI"],
        stars: 3,
        imageUrl: "image2.jpg",
        tags:["Kédjénou" , "kédjénou avec pondeuse"],
    },
    {
        id: "3",
        name: "Bieukosseu de poisson",
        price: 1200,
        favorite: false,
        cookTime: "30",
        origins: ["Attié" , "CI"],
        stars: 3,
        imageUrl: "image4.jpg",
        tags:["Bieukosseu" , "Bieukosseu de poisson"],
    },
    {
        id: "4",
        name: "Bieukosseu d'escargots",
        price: 1500,
        favorite: true,
        cookTime: "40",
        origins: ["Attié" , "CI"],
        stars: 4,
        imageUrl: "image3.jpg",
        tags:["Bieukosseu" , "Bieukosseu d'escargots"],
    },
    {
        id: "5",
        name: "Bawin",
        price: 1000,
        favorite: true,
        cookTime: "15-25",
        origins: ["Guéré" , "CI"],
        stars: 3.5,
        imageUrl: "image6.jpg",
        tags:["Bawin", "Bawin de poisson fumé"],
    },
    {
        id: "7",
        name: "Gouagouassou",
        price: 1200,
        favorite: true,
        cookTime: "40",
        origins: ["Baoulé" , "CI"],
        stars: 3.5,
        imageUrl: "image7.jpg",
        tags:["Gouagouassou" , "Gouagouassou de poisson fumé"],
    },
    {
        id: "8",
        name: "Tchiep de pondeuse",
        price: 1700,
        favorite: true,
        cookTime: "30-40",
        origins: ["Sénégal" , "SEN"],
        stars: 4,
        imageUrl: "image8.jpg",
        tags:["Tchiep" , "Tchiep de pondeuse"],
    },
    {
        id: "9",
        name: "Tchiep de poisson",
        price: 1300,
        favorite: true,
        cookTime: "30-40",
        origins: ["Sénégal" , "SEN"],
        stars: 3.5,
        imageUrl: "image9.jpg",
        tags:["Tchiep" , "Tchiep de poisson"],
    },
    {
        id: "10",
        name: "Yassa de boeuf",
        price: 1700,
        favorite: false,
        cookTime: "40",
        origins: ["Burkinabé" , "CI"],
        stars: 3,
        imageUrl: "image11.jpg",
        tags:["Yassa" , "Yassa de boeuf"],
    },
    {
        id: "11",
        name: "Yassa de poulet",
        price: 1700,
        favorite: true,
        cookTime: "40",
        origins: ["Ivoirien" , "CI"],
        stars: 3.5,
        imageUrl: "image10.jpg",
        tags:["Yassa" , "Yassa de poulet"],
    },
]

export default Data;